name: lxy1
description: "QQ风格课程管理页面"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_cors_image: ^0.3.13
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/652edf359d504b74a7044dd1fa73ce20.jpeg_tplv-a9rns2rl98-downsize_watermark_1_6_b.png
  uses-material-design: true
